//using System.Data.Entity;
//using System.Linq;
//using System.Web.Mvc;
//using ExpeditionMapper.Models.Domain;
//using ExpeditionMapper.DAL;
//using ExpeditionMapper.Models.ViewModels;
//using Kendo.Mvc.Extensions;
//using Kendo.Mvc.UI;

//namespace ExpeditionMapper.Controllers
//{
//    public class FallExpeditionController : Controller
//    {
//        private ExpeditionContext db = new ExpeditionContext();

//        // GET: /FallExpedition/
//        public ActionResult Index()
//        {
//            return View();
//        }

//        public ActionResult Expedition_Read([DataSourceRequest] DataSourceRequest request)
//        {
//            IQueryable<FallExpedition> programs = db.Programs.OfType<FallExpedition>();
//            return Json(programs.ToDataSourceResult(request));
//        }

//        [AcceptVerbs(HttpVerbs.Post)]
//        public ActionResult Expedition_Create([DataSourceRequest]DataSourceRequest request, ExpeditionViewModel expedition)
//        {
//            if (ModelState.IsValid)
//            {
//                // Create a new Expedition entity and set its properties from the posted FallExpedition Model
//                var entity = new FallExpedition
//                {
//                    Id = expedition.Id,
//                    Year = expedition.Year,
//                    Name = expedition.Name,
//                    Description = expedition.Description,
//                    GradeLevelId = expedition.GradeLevelId,
//                };
//                // Add the entity
//                db.Programs.Add(entity);
//                // Insert the entities in the database
//                db.SaveChanges();
//                // Get the Id generated by the database
//                expedition.Id = entity.Id;
//            }
//            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
//            return Json(new[] { expedition }.ToDataSourceResult(request, ModelState));
//        }

//        public ActionResult Expedition_Update([DataSourceRequest]DataSourceRequest request, ExpeditionViewModel expedition)
//        {
//            if (ModelState.IsValid)
//            {
//                // Create a new Product entity and set its properties from the posted ExpeditionViewModel
//                var entity = new FallExpedition
//                {
//                    Id = expedition.Id,
//                    Year = expedition.Year,
//                    Name = expedition.Name,
//                    Description = expedition.Description,
//                    GradeLevelId = expedition.GradeLevelId,
//                };
//                // Attach the entity
//                db.Programs.Attach(entity);
//                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
//                db.Entry(entity).State = EntityState.Modified;
//                // Update the entity in the database
//                db.SaveChanges();
//            }
//            // Return the updated entities. Also return any validation errors.
//            return Json(new[] { expedition }.ToDataSourceResult(request, ModelState));
//        }

//        public ActionResult Expedition_Destroy([DataSourceRequest]DataSourceRequest request, ExpeditionViewModel expedition)
//        {
//            if (ModelState.IsValid)
//            {
//                // Create a new Product entity and set its properties from the posted ProductViewModel
//                var entity = new FallExpedition
//                {
//                    Id = expedition.Id,
//                    Year = expedition.Year,
//                    Name = expedition.Name,
//                    Description = expedition.Description,
//                    GradeLevelId = expedition.GradeLevelId,
//                };
//                // Attach the entity
//                db.Programs.Attach(entity);
//                // Delete the entity
//                db.Programs.Remove(entity);
//                // Delete the entity in the database
//                db.SaveChanges();
//            }
//            // Return the removed product. Also return any validation errors.
//            return Json(new[] { expedition }.ToDataSourceResult(request, ModelState));
//        }

//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
//    }
//}
