using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ExpeditionMapper.Models.Domain;
using ExpeditionMapper.DAL;
using ExpeditionMapper.Models.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace ExpeditionMapper.Controllers
{
    public class ServiceLearningController : BaseController
    {
        private ExpeditionContext db = new ExpeditionContext();

        public ActionResult ServiceLearning_Read(int caseStudyId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<ServiceLearning> serviceLearning = db.ServiceLearnings.Where(f => f.CaseStudyId == caseStudyId);
            return Json(serviceLearning.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult ServiceLearning_Create(int caseStudyId, [DataSourceRequest]DataSourceRequest request, ServiceLearningViewModel serviceLearning)
        {
            if (ModelState.IsValid)
            {
                // Create a new Expedition entity and set its properties from the posted FallExpedition Model
                var entity = new ServiceLearning
                {
                    Id = serviceLearning.Id,
                    Name = serviceLearning.Name,
                    Description = serviceLearning.Description,
                    CaseStudyId = 1
                };
                // Add the entity
                db.ServiceLearnings.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                serviceLearning.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] { serviceLearning }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult ServiceLearning_Update(int caseStudyId, [DataSourceRequest]DataSourceRequest request, ServiceLearningViewModel serviceLearning)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ExpeditionViewModel
                var entity = new ServiceLearning
                {
                    Id = serviceLearning.Id,
                    Name = serviceLearning.Name,
                    Description = serviceLearning.Description,
                    CaseStudyId = 1
                };
                // Attach the entity
                db.ServiceLearnings.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] { serviceLearning }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult ServiceLearning_Destroy(int caseStudyId, [DataSourceRequest]DataSourceRequest request, ServiceLearningViewModel serviceLearning)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new ServiceLearning
                {
                    Id = serviceLearning.Id,
                    Name = serviceLearning.Name,
                    Description = serviceLearning.Description,
                    CaseStudyId = 1
                };

                // Attach the entity
                db.ServiceLearnings.Attach(entity);
                // Delete the entity
                db.ServiceLearnings.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] { serviceLearning }.ToDataSourceResult(request, ModelState));
        }
    }
}
