-- New Section Types
insert into sectiontypes values ('Leadership', 'Leadership')
insert into sectiontypes values ('BookClub', 'Book Club')
insert into sectiontypes values ('ReadingIntervention', 'Reading Intervention')
insert into sectiontypes values ('MathIntervention', 'Math Intervention')
insert into sectiontypes values ('ArtElementary', 'Art Elementary')
insert into sectiontypes values ('ArtMiddle', 'Art Middle')
insert into sectiontypes values ('MusicElementary', 'Music Elementary')
insert into sectiontypes values ('MusicMiddle', 'Music Middle')
insert into sectiontypes values ('PeElementary', 'PE Elementary')
insert into sectiontypes values ('PeMiddle', 'PE Middle')

-- Leadership
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'Leadership')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'Leadership')

-- BookClub
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'BookClub')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'BookClub')

-- ReadingIntervention
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'ReadingIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'ReadingIntervention')

-- MathIntervention
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'MathIntervention')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'MathIntervention')

-- ArtElementary
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'ArtElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'ArtElementary')

-- ArtMiddle
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'ArtMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'ArtMiddle')

-- MusicElementary
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'MusicElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'MusicElementary')

-- Music Middle
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'MusicMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'MusicMiddle')

-- PeElementary
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'PeElementary')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'PeElementary')

-- PeMiddle
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, 'K', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '1', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '2', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '3', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '4', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '5', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '6', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '7', 'PeMiddle')
insert into sections (Id, Year, GradeLevelId, SectionTypeId) values (newid(), 2014, '8', 'PeMiddle')
