using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.Data.Provider;
using Mapper21.Domain;
using Mapper21.Site.Models;

namespace Mapper21.Site.Controllers
{
    public class HabitController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult Habit_Read(Guid sectionId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<SectionHabit> habits = db.SectionHabits.Where(h => h.SectionId == sectionId);
            return Json(habits.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Habit_Create([DataSourceRequest] DataSourceRequest request,
            HabitViewModel habit)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new SectionHabit
                {
                    Id = Guid.NewGuid(),
                    HabitId = habit.HabitId,
                    Context = habit.Context,
                    SectionId = habit.SectionId
                };
                // Add the entity
                db.SectionHabits.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                habit.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {habit}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Habit_Update([DataSourceRequest] DataSourceRequest request,
            HabitViewModel updateHabit)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted Section Model
                var entity = new SectionHabit
                {
                    Id = updateHabit.Id,
                    HabitId = updateHabit.HabitId,
                    Context = updateHabit.Context,
                    SectionId = updateHabit.SectionId
                };
                // Attach the entity
                db.SectionHabits.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] { updateHabit }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Habit_Destroy(Guid sectionId, [DataSourceRequest] DataSourceRequest request,
            HabitViewModel deleteHabit)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new SectionHabit
                {
                    Id = deleteHabit.Id,
                    HabitId = deleteHabit.HabitId,
                    Context = deleteHabit.Context,
                    SectionId = deleteHabit.SectionId
                };
                // Attach the entity
                db.SectionHabits.Attach(entity);
                // Delete the entity
                db.SectionHabits.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] { deleteHabit }.ToDataSourceResult(request, ModelState));
        }
    }
}