using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.Business.Dto;
using Mapper21.Data.Provider;
using Mapper21.Domain;

namespace Mapper21.Site.Controllers
{
    public class LongTermTargetController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult LongTermTarget_Read(Guid subSectionStaId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<SubSectionLongTermTarget> longTermTargets =
                db.SubSectionLongTermTargets.Where(h => h.SubSectionStaId == subSectionStaId);
            return Json(longTermTargets.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult LongTermTarget_Create([DataSourceRequest] DataSourceRequest request,
            SubSectionLongTermTargetDto longTermTarget)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new SubSectionLongTermTarget
                {
                    Id = Guid.NewGuid(),
                    Name = longTermTarget.Name,
                    SubSectionStaId = longTermTarget.SubSectionStaId
                };
                // Add the entity
                db.SubSectionLongTermTargets.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                longTermTarget.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {longTermTarget}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult LongTermTarget_Update([DataSourceRequest] DataSourceRequest request,
            SubSectionLongTermTargetDto longTermTarget)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted Section Model
                var entity = new SubSectionLongTermTarget
                {
                    Id = longTermTarget.Id,
                    Name = longTermTarget.Name,
                    SubSectionStaId = longTermTarget.SubSectionStaId
                };
                // Attach the entity
                db.SubSectionLongTermTargets.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] {longTermTarget}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult LongTermTarget_Destroy([DataSourceRequest] DataSourceRequest request,
            SubSectionLongTermTargetDto longTermTarget)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new SubSectionLongTermTarget
                {
                    Id = longTermTarget.Id,
                    Name = longTermTarget.Name,
                    SubSectionStaId = longTermTarget.SubSectionStaId
                };
                // Attach the entity
                db.SubSectionLongTermTargets.Attach(entity);
                // Delete the entity
                db.SubSectionLongTermTargets.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] {longTermTarget}.ToDataSourceResult(request, ModelState));
        }
    }
}