drop table [dbo].[AspNetUserRoles]
drop table [dbo].[AspNetUserLogins]
drop table [dbo].[AspNetUserClaims]
drop table [dbo].[AspNetUsers]
drop table [dbo].[AspNetRoles]

drop table [dbo].[SectionGuidingQuestions]
drop table [dbo].[SectionHabits]
drop table [dbo].[SectionScienceBigIdeas]
drop table [dbo].[SectionSocialStudiesBigIdeas]
drop table [dbo].[SectionOtherBigIdeas]
drop table [dbo].[SubSectionAssessments]
drop table [dbo].[SubSectionExperts]
drop table [dbo].[SubSectionFieldworks]
drop table [dbo].[SubSectionGuidingQuestions]
drop table [dbo].[SubSectionHabits]
drop table [dbo].[SubSectionLongTermTargets]
drop table [dbo].[SubSectionShortTermTargets]
drop table [dbo].[SubSectionStandards]
drop table [dbo].[SubSectionStas]
drop table [dbo].[SubSectionStaGrids]
drop table [dbo].[SubSectionOtherBigIdeas]
drop table [dbo].[SubSectionServiceLearnings]
drop table [dbo].[SubSections]
drop table [dbo].[SubSectionTypes]
drop table [dbo].[Sections]
drop table [dbo].[SectionTypes]


drop table [dbo].[CommonCoreStandards]
drop table [dbo].[GradeLevels]
drop table [dbo].[Habits]
drop table [dbo].[ScienceBigIdeas]
drop table [dbo].[SocialStudiesBigIdeas]

drop table [dbo].[__MigrationHistory]