using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.BE.Domain;
using Mapper21.DAL.Provider;
using Mapper21.UI.Models;

namespace Mapper21.UI.Controllers
{
    public class ExpertController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult Expert_Read(int caseStudyId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<SubSectionExpert> expert = db.SubSectionExperts.Where(f => f.SubSectionId == caseStudyId);
            return Json(expert.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Expert_Create([DataSourceRequest] DataSourceRequest request, ExpertViewModel expert)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new SubSectionExpert
                {
                    Id = expert.Id,
                    Name = expert.Name,
                    Description = expert.Description,
                    SubSectionId = expert.SubSectionId
                };
                // Add the entity
                db.SubSectionExperts.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                expert.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {expert}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Expert_Update([DataSourceRequest] DataSourceRequest request, ExpertViewModel expert)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted SectionViewModel
                var entity = new SubSectionExpert
                {
                    Id = expert.Id,
                    Name = expert.Name,
                    Description = expert.Description,
                    SubSectionId = expert.SubSectionId
                };
                // Attach the entity
                db.SubSectionExperts.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] {expert}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Expert_Destroy([DataSourceRequest] DataSourceRequest request, ExpertViewModel expert)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new SubSectionExpert
                {
                    Id = expert.Id,
                    Name = expert.Name,
                    Description = expert.Description,
                    SubSectionId = expert.SubSectionId
                };
                // Attach the entity
                db.SubSectionExperts.Attach(entity);
                // Delete the entity
                db.SubSectionExperts.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] {expert}.ToDataSourceResult(request, ModelState));
        }
    }
}