using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.BE.Domain;
using Mapper21.DAL.Provider;
using Mapper21.UI.Models;

namespace Mapper21.UI.Controllers
{
    public class HabitController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult SectionHabit_Read(int sectionId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<Habit> habits = db.Habits.Where(h => h.SectionId == sectionId);
            return Json(habits.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Habit_Create([DataSourceRequest] DataSourceRequest request,
            HabitViewModel habit)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new Habit
                {
                    Id = habit.Id,
                    Description = habit.Habit,
                    Rationale = habit.Rationale,
                    SectionId = habit.SectionId
                };
                // Add the entity
                db.Habits.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                habit.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {habit}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Habit_Update([DataSourceRequest] DataSourceRequest request,
            HabitViewModel habit)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted Section Model
                var entity = new Habit
                {
                    Id = habit.Id,
                    Description = habit.Habit,
                    Rationale = habit.Rationale,
                    SectionId = habit.SectionId
                };
                // Attach the entity
                db.Habits.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] {habit}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Habit_Destroy(int sectionId, [DataSourceRequest] DataSourceRequest request,
            HabitViewModel habit)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new Habit
                {
                    Id = habit.Id,
                    Description = habit.Habit,
                    Rationale = habit.Rationale,
                    SectionId = habit.SectionId
                };
                // Attach the entity
                db.Habits.Attach(entity);
                // Delete the entity
                db.Habits.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] {habit}.ToDataSourceResult(request, ModelState));
        }
    }
}