using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.BE.Domain;
using Mapper21.DAL.Provider;
using Mapper21.UI.Models;

namespace Mapper21.UI.Controllers
{
    public class StandardController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult Standard_Read(Guid subSectionStaId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<SubSectionStandard> standards = db.SubSectionStandards.Where(h => h.SubSectionStaId == subSectionStaId);
            return Json(standards.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Standard_Create([DataSourceRequest] DataSourceRequest request,
            StandardViewModel createStandard)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new SubSectionStandard
                {
                    Id = createStandard.Id,
                    CommonCoreStandardId = createStandard.CommonCoreStandardId,
                    SubSectionStaId = createStandard.SubSectionStaId
                };
                // Add the entity
                db.SubSectionStandards.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                createStandard.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] { createStandard }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Standard_Update([DataSourceRequest] DataSourceRequest request,
            StandardViewModel updateStandard)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted SectionViewModel
                var entity = new SubSectionStandard
                {
                    Id = updateStandard.Id,
                    CommonCoreStandardId = updateStandard.CommonCoreStandardId,
                    SubSectionStaId = updateStandard.SubSectionStaId
                };
                // Attach the entity
                db.SubSectionStandards.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] { updateStandard }.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Standard_Destroy([DataSourceRequest] DataSourceRequest request,
            StandardViewModel deleteStandard)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new SubSectionStandard
                {
                    Id = deleteStandard.Id,
                    CommonCoreStandardId = deleteStandard.CommonCoreStandardId,
                    SubSectionStaId = deleteStandard.SubSectionStaId
                };
                // Attach the entity
                db.SubSectionStandards.Attach(entity);
                // Delete the entity
                db.SubSectionStandards.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] { deleteStandard }.ToDataSourceResult(request, ModelState));
        }
    }
}