using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.BE.Domain;
using Mapper21.DAL.Provider;
using Mapper21.UI.Models;

namespace Mapper21.UI.Controllers
{
    public class SubSectionGuidingQuestionController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult GuidingQuestion_Read(Guid subSectionId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<SubSectionGuidingQuestion> guidingQuestions = db.SubSectionGuidingQuestions.Where(g => g.SubSectionId == subSectionId);
            return Json(guidingQuestions.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult GuidingQuestion_Create(Guid subSectionId, [DataSourceRequest] DataSourceRequest request,
            GuidingQuestionSubSectionViewModel guidingQuestion)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new SubSectionGuidingQuestion
                {
                    Id = Guid.NewGuid(),
                    Name = guidingQuestion.Name,
                    SubSectionId = guidingQuestion.SubSectionId
                };
                // Add the entity
                db.SubSectionGuidingQuestions.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                guidingQuestion.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {guidingQuestion}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult GuidingQuestion_Update([DataSourceRequest] DataSourceRequest request,
            GuidingQuestionSubSectionViewModel guidingQuestion)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted Section Model
                var entity = new SubSectionGuidingQuestion
                {
                    Id = guidingQuestion.Id,
                    Name = guidingQuestion.Name,
                    SubSectionId = guidingQuestion.SubSectionId
                };
                // Attach the entity
                db.SubSectionGuidingQuestions.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] {guidingQuestion}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult GuidingQuestion_Destroy([DataSourceRequest] DataSourceRequest request,
            GuidingQuestionSubSectionViewModel guidingQuestion)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new SubSectionGuidingQuestion
                {
                    Id = guidingQuestion.Id,
                    Name = guidingQuestion.Name,
                    SubSectionId = guidingQuestion.SubSectionId
                };
                // Attach the entity
                db.SubSectionGuidingQuestions.Attach(entity);
                // Delete the entity
                db.SubSectionGuidingQuestions.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] {guidingQuestion}.ToDataSourceResult(request, ModelState));
        }
    }
}