// <auto-generated />
namespace Mapper21.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class DomainChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DomainChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201408092323041_DomainChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
