using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.BE.Domain;
using Mapper21.DAL.Provider;
using Mapper21.UI.Models;

namespace Mapper21.UI.Controllers
{
    public class SocialStudiesBigIdeaController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult SocialStudiesBigIdea_Read(int sectionId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<SocialStudiesBigIdea> socialStudiesBigIdeas =
                db.SocialStudiesBigIdeas.Where(b => b.SectionId == sectionId);
            return Json(socialStudiesBigIdeas.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult SocialStudiesBigIdea_Create([DataSourceRequest] DataSourceRequest request,
            SocialStudiesBigIdeaViewModel socialStudiesBigIdea)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new SocialStudiesBigIdea
                {
                    Id = socialStudiesBigIdea.Id,
                    Idea = socialStudiesBigIdea.Idea,
                    Rationale = socialStudiesBigIdea.Rationale,
                    SectionId = socialStudiesBigIdea.SectionId
                };
                // Add the entity
                db.SocialStudiesBigIdeas.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                socialStudiesBigIdea.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {socialStudiesBigIdea}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult SocialStudiesBigIdea_Update([DataSourceRequest] DataSourceRequest request,
            SocialStudiesBigIdeaViewModel socialStudiesBigIdea)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted Section Model
                var entity = new SocialStudiesBigIdea
                {
                    Id = socialStudiesBigIdea.Id,
                    Idea = socialStudiesBigIdea.Idea,
                    Rationale = socialStudiesBigIdea.Rationale,
                    SectionId = socialStudiesBigIdea.SectionId
                };
                // Attach the entity
                db.SocialStudiesBigIdeas.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] {socialStudiesBigIdea}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult SocialStudiesBigIdea_Destroy([DataSourceRequest] DataSourceRequest request,
            SocialStudiesBigIdeaViewModel socialStudiesBigIdea)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new SocialStudiesBigIdea
                {
                    Id = socialStudiesBigIdea.Id,
                    Idea = socialStudiesBigIdea.Idea,
                    Rationale = socialStudiesBigIdea.Rationale,
                    SectionId = socialStudiesBigIdea.SectionId
                };
                // Attach the entity
                db.SocialStudiesBigIdeas.Attach(entity);
                // Delete the entity
                db.SocialStudiesBigIdeas.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] {socialStudiesBigIdea}.ToDataSourceResult(request, ModelState));
        }
    }
}