using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Mapper21.BE.Domain;
using Mapper21.DAL.Provider;
using Mapper21.UI.Models;

namespace Mapper21.UI.Controllers
{
    public class StandardController : BaseController
    {
        private readonly Mapper21Context db = new Mapper21Context();

        public ActionResult Standard_Read(int staCollectionId, [DataSourceRequest] DataSourceRequest request)
        {
            IQueryable<Standard> standards = db.Standards.Where(h => h.StaCollectionId == staCollectionId);
            return Json(standards.ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Standard_Create([DataSourceRequest] DataSourceRequest request,
            StandardViewModel standard)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted Section Model
                var entity = new Standard
                {
                    Id = standard.Id,
                    Name = standard.Name,
                    StaCollectionId = standard.StaCollectionId
                };
                // Add the entity
                db.Standards.Add(entity);
                // Insert the entities in the database
                db.SaveChanges();
                // Get the Id generated by the database
                standard.Id = entity.Id;
            }
            // Return the inserted entities. The grid needs the generated ID. Also return any validation errors.
            return Json(new[] {standard}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Standard_Update([DataSourceRequest] DataSourceRequest request,
            StandardViewModel standard)
        {
            if (ModelState.IsValid)
            {
                // Create a new Section entity and set its properties from the posted SectionViewModel
                var entity = new Standard
                {
                    Id = standard.Id,
                    Name = standard.Name,
                    StaCollectionId = standard.StaCollectionId
                };
                // Attach the entity
                db.Standards.Attach(entity);
                // Change its state to Modified so Entity Framework can update the existing product instead of creating a new one
                db.Entry(entity).State = EntityState.Modified;
                // Update the entity in the database
                db.SaveChanges();
            }
            // Return the updated entities. Also return any validation errors.
            return Json(new[] {standard}.ToDataSourceResult(request, ModelState));
        }

        public ActionResult Standard_Destroy([DataSourceRequest] DataSourceRequest request,
            StandardViewModel standard)
        {
            if (ModelState.IsValid)
            {
                // Create a new Product entity and set its properties from the posted ProductViewModel
                var entity = new Standard
                {
                    Id = standard.Id,
                    Name = standard.Name,
                    StaCollectionId = standard.StaCollectionId
                };
                // Attach the entity
                db.Standards.Attach(entity);
                // Delete the entity
                db.Standards.Remove(entity);
                // Delete the entity in the database
                db.SaveChanges();
            }
            // Return the removed product. Also return any validation errors.
            return Json(new[] {standard}.ToDataSourceResult(request, ModelState));
        }
    }
}